version: '0.1'

services:

# Use postgres/example user/password credentials
  postgres:
    image: "postgres:latest"
    container_name: postgres
    restart: always
    volumes: 
      - "postgresql:/var/lib/postgres"
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

# Use root/example as user/password credentials
  mysql:
    image: "mysql:latest"
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
      - "mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

volumes:
  mysql:
    external: true
  postgresql:
    external: true



