version: '0.1'

services:

# Use postgres/example user/password credentials
  postgres:
    image: "postgres:11"
    container_name: postgres
    env_file:
      - ./.env
    restart: always
    volumes: 
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - 5432:5432

# Use root/example as user/password credentials
  mysql:
    image: "mysql:8.0"
    container_name: mysql
    env_file:
      - ./.env
    restart: always
    volumes: 
      - "msql-data:/var/lib/mysql"
    ports:
      - 3306:3306

volumes:
  postgres-data:
      external: true
  msql-data:
    external: true
