insert into costs (id, name, price) values (1, 'Jeth', 24);
insert into costs (id, name, price) values (2, 'Orella', 43);
insert into costs (id, name, price) values (3, 'Stacey', 22);
insert into costs (id, name, price) values (4, 'Joan', 10);
insert into costs (id, name, price) values (5, 'Paxon', 20);
insert into costs (id, name, price) values (6, 'Shalna', 93);
insert into costs (id, name, price) values (7, 'Herby', 40);
insert into costs (id, name, price) values (8, 'Scott', 25);
insert into costs (id, name, price) values (9, 'Kristi', 98);
insert into costs (id, name, price) values (10, 'Andriette', 42);
insert into costs (id, name, price) values (11, 'Boyd', 8);
insert into costs (id, name, price) values (12, 'Patricia', 13);
insert into costs (id, name, price) values (13, 'Kameko', 79);
insert into costs (id, name, price) values (14, 'Amalita', 6);
insert into costs (id, name, price) values (15, 'Jade', 11);
insert into costs (id, name, price) values (16, 'Kyrstin', 22);
insert into costs (id, name, price) values (17, 'Suzann', 35);
insert into costs (id, name, price) values (18, 'Waly', 68);
insert into costs (id, name, price) values (19, 'Mab', 12);
insert into costs (id, name, price) values (20, 'Carita', 71);

insert into products (name, status, quantity) values ('Tomatoes - Yellow Hot House', 0, 2);
insert into products (name, status, quantity) values ('Burger Veggie', 1, 2);
insert into products (name, status, quantity) values ('Brandy Apricot', 0, 2);
insert into products (name, status, quantity) values ('Dikon', 1, 9);
insert into products (name, status, quantity) values ('Pastry - Banana Muffin - Mini', 0, 9);
insert into products (name, status, quantity) values ('Gin - Gilbeys London, Dry', 0, 5);
insert into products (name, status, quantity) values ('Sole - Dover, Whole, Fresh', 0, 1);
insert into products (name, status, quantity) values ('Water - Mineral, Carbonated', 0);
insert into products (name, status, quantity) values ('Wasabi Powder', 0, 3);
insert into products (name, status, quantity) values ('Trueblue - Blueberry', 0, 42);
insert into products (name, status, quantity) values ('Cleaner - Pine Sol', 1, 77);
insert into products (name, status, quantity) values ('Beer - Creemore', 0, 6);
insert into products (name, status, quantity) values ('Wine - Semi Dry Riesling Vineland', 1, 79);
insert into products (name, status, quantity) values ('Lettuce - Romaine', 0, 18);
insert into products (name, status, quantity) values ('Pasta - Penne, Lisce, Dry', 0, 87);
insert into products (name, status, quantity) values ('Sauce - Hp', 0, 60);
insert into products (name, status, quantity) values ('Grouper - Fresh', 0, 54);
insert into products (name, status, quantity) values ('Island Oasis - Lemonade', 0, 71);
insert into products (name, status, quantity) values ('Sauce - Soya, Light', 1, 51);
insert into products (name, status, quantity) values ('Mop Head - Cotton, 24 Oz', 1, 11);